export const ActionTypes = {
  GET_PRODUCTS: "store/GET_BOOKS",
  CANCEL_PRODUCT: "store/CANCEL_PRODUCT",
  //BOOKING
  OPEN_BOOK_PRODUCT: "store/OPEN_BOOK_PRODUCTS",
  OPEN_BOOK_PRICE: "store/OPEN_BOOK_PRICE",
  CONFIRM_BOOK_PRICE: "store/CONFIRM_BOOK_PRICE",
  CANCEL_BOOK_PRICE: "store/CANCEL_BOOK_PRICE",
  //RETURNING
  OPEN_RETURN_PRODUCT: "store/OPEN_RETURN_PRODUCT",
  OPEN_RETURN_PRICE: "store/OPEN_RETURN_PRICE",
  CONFIRM_RETURN_PRICE: "store/CONFIRM_RETURN_PRICE",
};
